<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <PeekMeowVersionFile>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\VERSION'))</PeekMeowVersionFile>
    <PeekMeowBuildFile>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\BUILD'))</PeekMeowBuildFile>
    <PeekMeowVersion>$([System.IO.File]::ReadAllText('$(PeekMeowVersionFile)').Trim())</PeekMeowVersion>
    <PeekMeowBuild>$([System.IO.File]::ReadAllText('$(PeekMeowBuildFile)').Trim())</PeekMeowBuild>
    <Version>0.1.0.$(PeekMeowBuild)</Version>
    <AssemblyVersion>0.1.0.$(PeekMeowBuild)</AssemblyVersion>
    <FileVersion>0.1.0.$(PeekMeowBuild)</FileVersion>
    <InformationalVersion>$(PeekMeowVersion)</InformationalVersion>
    <Product>PeekMeow</Product>
    <Company>PeekMeow</Company>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <Target Name="SetPeekMeowCommit" BeforeTargets="GenerateAssemblyInfo">
    <Exec Command="git rev-parse HEAD" WorkingDirectory="$(MSBuildThisFileDirectory).." ConsoleToMSBuild="true" IgnoreExitCode="true" StandardOutputImportance="low">
      <Output TaskParameter="ConsoleOutput" PropertyName="SourceRevisionId" />
    </Exec>
    <PropertyGroup>
      <SourceRevisionId>$([System.String]::Copy('$(SourceRevisionId)').Trim())</SourceRevisionId>
    </PropertyGroup>
  </Target>
</Project>
